In [42]:
from tensorflow import keras
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import glob 
import numpy as np
from os import listdir,makedirs
from os.path import isfile,join
from numpy import *
from PIL import Image
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import random
import cv2
import os 

In [43]:
path_2="/home/dashan/Desktop/modified_data"

IMG_SIZE=300

def label_img(name):
	if name[0:2]=="NL":
		return np.array([1,0,0,0])
	elif name[0:2]=="ca":
		return np.array([0,1,0,0])
	elif name[0:2]=="Gl":
		return np.array([0,0,1,0])
	else:
		return np.array([0,0,0,1])
def load_training_data(arg):
	train_data=[]
	DIR=path_2+"/"+arg
	for img in os.listdir(DIR):
		label=label_img(img)
		path=os.path.join(DIR,img)
		img=Image.open(path)
		img=img.convert('L')
		img.resize((IMG_SIZE,IMG_SIZE),Image.ANTIALIAS)
		train_data.append([np.array(img),label])
# 		flip_img=Image.open(path)
# 		flip_img=flip_img.convert('L')
# 		flip_img = flip_img.resize((IMG_SIZE, IMG_SIZE), Image.ANTIALIAS)
# 		flip_img = np.array(flip_img)
# 		flip_img = np.fliplr(flip_img)
# 		train_data.append([flip_img, label])
	shuffle(train_data)
	return train_data
a=load_training_data("1_normal")
b=load_training_data("2_cataract")
c=load_training_data("2_glaucoma")
d=load_training_data("3_retina_disease")


In [18]:
train_data=[]
for i in range(80):
    train_data.append(a[i])
for i in range(80):
    train_data.append(b[i])
for i in range(80):
    train_data.append(c[i])
for i in range(80):
    train_data.append(d[i])
shuffle(train_data)
test_data=[]
val_data=[]
for i in range(80,90):
    test_data.append(a[i])
for i in range(80,90):
    test_data.append(b[i])
for i in range(80,90):
    test_data.append(c[i])
for i in range(80,90):
    test_data.append(d[i])
shuffle(test_data)

for i in range(90,100):
    val_data.append(a[i])
for i in range(90,100):
    val_data.append(b[i])
for i in range(90,100):
    val_data.append(c[i])
for i in range(90,100):
    val_data.append(d[i])
shuffle(val_data)

[[array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 1, ..., 0, 0, 0],
         [0, 0, 1, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [1, 0, 0, ..., 0, 0, 0],
         [0, 0, 1, ..., 0, 0, 0]], dtype=uint8),
  array([0, 0, 0, 1])],
 [array([[0, 0, 0, ..., 0, 0, 0],
         [1, 0, 0, ..., 0, 0, 0],
         [0, 0, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]], dtype=uint8),
  array([0, 1, 0, 0])],
 [array([[1, 0, 0, ..., 0, 1, 1],
         [1, 0, 0, ..., 0, 0, 0],
         [1, 0, 0, ..., 0, 0, 0],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 0, 1, 1]], dtype=uint8),
  array([0, 0, 1, 0])],
 [array([[1, 1, 0, ..., 0, 0, 1],
         [0, 0, 0, ..., 0, 0, 1],
         [0, 0, 0, ..., 0, 0, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 0, ..., 1, 1, 1]], dtype=uint

In [44]:
trainImages = np.array([i[0] for i in train_data]).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
trainLabels = np.array([i[1] for i in train_data])

In [45]:
testImages =  np.array([i[0] for i in test_data]).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
testLabels = np.array([i[1] for i in test_data])

In [46]:
val_Images =  np.array([i[0] for i in val_data]).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
val_Labels = np.array([i[1] for i in val_data])

In [47]:
## MODEL
from keras import regularizers

In [49]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.layers.normalization import BatchNormalization

# IMG_SIZE=300
model = Sequential()
model.add(Conv2D(32, kernel_size = (3, 3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 1),kernel_regularizer=regularizers.l2(0.001)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size=(3,3), activation='relu',kernel_regularizer=regularizers.l2(0.001)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size=(3,3), activation='relu',kernel_regularizer=regularizers.l2(0.001)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(96, kernel_size=(3,3), activation='relu',kernel_regularizer=regularizers.l2(0.001)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(32, kernel_size=(3,3), activation='relu',kernel_regularizer=regularizers.l2(0.001)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Flatten())
# model.add(Dense(512, activation='relu',kernel_regularizer=regularizers.l2(0.001)))
# model.add(Dropout(0.3))
model.add(Dense(256, activation='relu',kernel_regularizer=regularizers.l2(0.001)))
model.add(Dropout(0.3))
model.add(Dense(128, activation='relu',kernel_regularizer=regularizers.l2(0.001)))
model.add(Dropout(0.3))
model.add(Dense(4, activation = 'sigmoid'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
print("compile to ho gya ")
model.summary()

compile to ho gya 
Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_60 (Conv2D)           (None, 298, 298, 32)      320       
_________________________________________________________________
max_pooling2d_58 (MaxPooling (None, 149, 149, 32)      0         
_________________________________________________________________
batch_normalization_58 (Batc (None, 149, 149, 32)      128       
_________________________________________________________________
conv2d_61 (Conv2D)           (None, 147, 147, 64)      18496     
_________________________________________________________________
max_pooling2d_59 (MaxPooling (None, 73, 73, 64)        0         
_________________________________________________________________
batch_normalization_59 (Batc (None, 73, 73, 64)        256       
_________________________________________________________________
conv2d_62 (Conv2D)           (None

In [ ]:
history = model.fit(trainImages, trainLabels,
                    batch_size=10,
                    epochs=100,
                    # We pass some validation for
                    # monitoring validation loss and metrics
                    # at the end of each epoch
                    validation_data=(val_Images, val_Labels),verbose=1)

Train on 600 samples, validate on 100 samples
Epoch 1/100
600/600 [==============================] - 100s 167ms/step - loss: 2.2114 - accuracy: 0.2100 - val_loss: 2.1305 - val_accuracy: 0.2500
Epoch 2/100
600/600 [==============================] - 96s 159ms/step - loss: 2.0978 - accuracy: 0.2333 - val_loss: 2.0477 - val_accuracy: 0.2000
Epoch 3/100
600/600 [==============================] - 97s 162ms/step - loss: 2.0108 - accuracy: 0.2400 - val_loss: 1.9721 - val_accuracy: 0.1800
Epoch 4/100
600/600 [==============================] - 105s 175ms/step - loss: 1.9372 - accuracy: 0.2283 - val_loss: 1.9024 - val_accuracy: 0.1800
Epoch 5/100
600/600 [==============================] - 94s 156ms/step - loss: 1.8729 - accuracy: 0.2483 - val_loss: 1.8414 - val_accuracy: 0.2000
Epoch 6/100
600/600 [==============================] - 119s 198ms/step - loss: 1.8260 - accuracy: 0.2583 - val_loss: 1.7871 - val_accuracy: 0.2700
Epoch 7/100
200/600 [=========>....................] - ETA: 1:05 - loss: 1.