In [20]:
from tensorflow import keras
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import glob 
import numpy as np
from os import listdir,makedirs
from os.path import isfile,join
from numpy import *
from PIL import Image
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import random
import cv2
import os 

In [21]:
path_2="/home/dashan/Desktop/modified_data"

IMG_SIZE=300

def label_img(name):
	if name[0:2]=="no":
		return np.array([1,0])
	elif name[0:2]=="ca":
		return np.array([0,1])

def load_training_data(arg):
	train_data=[]
	DIR=path_2+"/"+arg
	for img in os.listdir(DIR):
		label=label_img(img)
		path=os.path.join(DIR,img)
		img=Image.open(path)
		img=img.convert('L')
		img.resize((IMG_SIZE,IMG_SIZE),Image.ANTIALIAS)
		train_data.append([np.array(img),label])
	shuffle(train_data)
	return train_data
a=load_training_data("1_normal")
b=load_training_data("2_cataract")

In [22]:
print(len(a),len(b))
train_data=[]
shuffle(a)
for i in range(len(a)-250):
	train_data.append(a[i])
shuffle(train_data)
for i in range(len(b)-250):
	train_data.append(b[i])
shuffle(train_data)
test_data=[]
for i in range(len(a)-250,len(a)):
    test_data.append(a[i])
for i in range(len(b)-250,len(b)):
    test_data.append(b[i])
shuffle(test_data)

2000 2000


[[array([[1, 1, 1, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [1, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
  array([0, 1])],
 [array([[20, 14,  6, ...,  4, 19,  8],
         [13,  4, 42, ...,  1,  4,  8],
         [13,  5,  8, ...,  9,  8, 22],
         ...,
         [ 7,  5,  8, ...,  8, 15, 11],
         [ 5,  7,  7, ...,  2,  8, 15],
         [12, 16, 16, ...,  5, 11,  8]], dtype=uint8),
  array([1, 0])],
 [array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
  array([0, 1])],
 [array([[10,  4, 16, ..., 17,  9,  6],
         [23, 12, 10, ...,  4, 18, 14],
         [ 5,  6,  4, ..., 18,  5,  7],
         ...,
         [16,  7, 17, ..., 17, 21, 12],
         [10,  8, 24, ...,  8, 15,  6

In [23]:
print(len(test_data))
testImages = np.array([i[0] for i in test_data]).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
testLabels = np.array([i[1] for i in test_data])

500


In [24]:
print(len(train_data))
trainImages = np.array([i[0] for i in train_data]).reshape(-1, IMG_SIZE, IMG_SIZE, 1)
trainLabels = np.array([i[1] for i in train_data])

3500


In [25]:
from keras.models import Sequential
from keras import regularizers
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.layers.normalization import BatchNormalization

# IMG_SIZE=300
model = Sequential()
model.add(Conv2D(32, kernel_size = (3, 3), activation='sigmoid', input_shape=(IMG_SIZE, IMG_SIZE, 1),kernel_regularizer=regularizers.l2(0.01)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size=(3,3), activation='sigmoid',kernel_regularizer=regularizers.l2(0.01)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(64, kernel_size=(3,3), activation='sigmoid',kernel_regularizer=regularizers.l2(0.01)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(96, kernel_size=(3,3), activation='sigmoid',kernel_regularizer=regularizers.l2(0.01)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Conv2D(32, kernel_size=(3,3), activation='sigmoid',kernel_regularizer=regularizers.l2(0.01)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Flatten())
# model.add(Dense(512, activation='relu',kernel_regularizer=regularizers.l2(0.001)))
# model.add(Dropout(0.3))
model.add(Dense(256, activation='sigmoid',kernel_regularizer=regularizers.l2(0.01)))
model.add(Dropout(0.3))
model.add(Dense(128, activation='sigmoid',kernel_regularizer=regularizers.l2(0.01)))
model.add(Dropout(0.3))
model.add(Dense(2, activation = 'sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics = ['accuracy'])
print("compile to ho gya ")
model.summary()

compile to ho gya 
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_16 (Conv2D)           (None, 298, 298, 32)      320       
_________________________________________________________________
max_pooling2d_16 (MaxPooling (None, 149, 149, 32)      0         
_________________________________________________________________
batch_normalization_16 (Batc (None, 149, 149, 32)      128       
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 147, 147, 64)      18496     
_________________________________________________________________
max_pooling2d_17 (MaxPooling (None, 73, 73, 64)        0         
_________________________________________________________________
batch_normalization_17 (Batc (None, 73, 73, 64)        256       
_________________________________________________________________
conv2d_18 (Conv2D)           (None,

In [26]:
# from sklearn.model_selection import train_test_split
# trainX, testX, trainY, testY = train_test_split(trainImages, trainLabels, test_size=0.125,random_state=1234)
# testX=

In [ ]:
history = model.fit(trainImages, trainLabels,
                    batch_size=10,
                    epochs=100,
                    # We pass some validation for
                    # monitoring validation loss and metrics
                    # at the end of each epoch
                    validation_data=(testImages,testLabels),verbose=1)

Train on 3500 samples, validate on 500 samples
Epoch 1/100
3500/3500 [==============================] - 641s 183ms/step - loss: 2.1981 - accuracy: 0.7329 - val_loss: 1.5270 - val_accuracy: 0.5000
Epoch 2/100
 130/3500 [>.............................] - ETA: 11:26 - loss: 0.8145 - accuracy: 0.7462

In [ ]:
model.save("model_augmented.h5")